apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pbk1gqkhq-python 
  janus-idp.io/tekton: pbk1gqkhq-python
  backstage.io/kubernetes-id: pbk1gqkhq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pbk1gqkhq-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  