apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: pbk1gqkhq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pbk1gqkhq-python 
  name: pbk1gqkhq-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: pbk1gqkhq-python
    weight: 100 
