apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pbk1gqkhq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pbk1gqkhq-python 
  name: pbk1gqkhq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pbk1gqkhq-python 
